### ISSUE TITLE
Preview of Emoji Next to Highlighted Emoji

### ISSUE THREAD

**Issue by roseusgarcia** [Pext/pext_module_emoji#5]
Already spoke with @TheLastProject for this feature, but I think it would look nice to have this feature.
Maybe under the emoji it can have tags like for the category belongs in like for the Pisces  emoji under that preview screen  it can have the tag "Astrology Signs".

Attached is an example of what I mean and it would definitely  look really nice for emoji. 

<img width="882" alt="screen shot 2018-06-27 at 5 13 52 pm" src="https://user-images.githubusercontent.com/37086530/42000102-a3ff0fc0-7a2d-11e8-8d78-0c6e0683419f.png">

**Comment by TheLastProject** [comment]
This was fixed in https://github.com/Pext/pext_module_emoji/commit/9cd6b6d7410091964bfdfcb0d381d6e994a99372, forgot to close this issue.
